default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_typing_development
  username: rails_typing
  host: localhost
  pool: 5
  password: '123'

test:
  <<: *default
  database: rails_typing_test

production:
  <<: *default
  database: rails_typing_production
  username: rails_typing
  password: <%= ENV["RAILS_TYPING_DATABASE_PASSWORD"] %>